"""
Icons from Material Design Icons (https://fonts.google.com/icons).
"""

DELETE = "delete"
CLOSE = "close"
DEBUG = "debug"
LINK = "link"
STAR = "star"
OPEN_IN_NEW = "open_in_new"
EDIT = "edit"
ADD = "add"
FOLDER = "folder"
FOLDER_OPEN = "folder_open"
UPLOAD_FILE = "upload_file"
SAVE_AS = "save_as"
SETTINGS = "settings"
DONE = "done"
FAVORITE = "favorite"
APPS = "apps"
REFRESH = "refresh"
MORE_VERTCAL = "more_vert"
MORE_HORIZONTAL = "more_horiz"
